import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import '../public/styles.css';
import './styles.css';

const params = new URLSearchParams(location.search);
const requestId = params.get('request') || sessionStorage.getItem('vivintoneRequest') || '';
const initialToken = params.get('token') || sessionStorage.getItem(`vivintoneToken:${requestId}`) || '';
if (params.get('token') && requestId) {
  sessionStorage.setItem('vivintoneRequest', requestId);
  sessionStorage.setItem(`vivintoneToken:${requestId}`, params.get('token'));
  history.replaceState({}, '', `/request.html?request=${encodeURIComponent(requestId)}`);
}

function Portal() {
  const [token] = useState(initialToken);
  const [request, setRequest] = useState(null);
  const [mode, setMode] = useState('');
  const [error, setError] = useState('');
  const [success, setSuccess] = useState(null);
  const load = () => fetch(`/api/reimbursements/${encodeURIComponent(requestId)}?token=${encodeURIComponent(token)}`, { cache: 'no-store' }).then(async response => {
    const data = await response.json(); if (!response.ok) throw new Error(data.error || 'request_unavailable'); setRequest(data.request);
  }).catch(err => setError(err.message.replaceAll('_', ' ')));
  useEffect(load, []);
  if (error && !request) return <Shell><div className="portal-card"><h1>This private link could not be opened.</h1><p>{error}. Ask the VivintOne Hardware Lab to resend the approval email.</p></div></Shell>;
  if (!request) return <Shell><div className="portal-card"><p>Opening your private hardware request…</p></div></Shell>;
  return <Shell><div className="portal-head"><p className="eyebrow">Private contributor portal</p><h1>{request.requestId}</h1><p><strong>{request.productName}</strong> · {request.modelNumber}</p><div className="status-line"><span>Shipping: {request.carrierStatus?.replaceAll('_', ' ') || 'not started'}</span><span>Reimbursement: {request.reimbursementStatus?.replaceAll('_', ' ') || 'not requested'}</span></div></div>
    {success && <div className="portal-card success" role="status"><strong>{success.message}</strong>{success.labelUrl && <><p>Your label is also being emailed to you.</p><a className="button" href={success.labelUrl} target="_blank" rel="noreferrer">Open prepaid label</a>{success.trackingNumber && <p>Tracking: <code>{success.trackingNumber}</code></p>}</>}</div>}
    {!request.shippingMethod || request.shippingMethod === 'prepaid_requested' ? <div className="portal-card"><h2>How would you like to ship?</h2><p>Choose one path. Your approved request permits one guarded prepaid label, or you can use your own postage.</p><div className="choice-grid"><button onClick={() => setMode('prepaid')}><strong>Get a prepaid label</strong><span>Enter the return address and packed measurements. VivintOne validates them, buys one eligible label within the approved cap, and displays it immediately.</span></button><button onClick={() => setMode('manual')}><strong>Ship it myself</strong><span>Provide carrier tracking, then choose whether to request reimbursement after physical receipt.</span></button></div></div> : <ShipmentStatus request={request} requestId={requestId} token={token} setError={setError} />}
    {mode === 'prepaid' && <Prepaid requestId={requestId} token={token} done={result => { setSuccess(result); setMode(''); load(); }} setError={setError} />}
    {mode === 'manual' && <Manual requestId={requestId} token={token} request={request} done={message => { setSuccess({ message }); setMode(''); load(); }} setError={setError} />}
    {request.shippingMethod === 'self_shipped' && request.reimbursementStatus !== 'paid' && <Manual requestId={requestId} token={token} request={request} trackingDone done={message => { setSuccess({ message }); load(); }} setError={setError} />}
    {error && <p className="error" role="alert">{error}</p>}
  </Shell>;
}

function ShipmentStatus({ request, requestId, token, setError }) {
  const [loadingLabel, setLoadingLabel] = useState(false);
  const openLabel = async () => { setLoadingLabel(true); setError(''); try { const response=await fetch(`/api/shipments/${encodeURIComponent(requestId)}/label-url`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token})}); const data=await response.json(); if(!response.ok) throw new Error(data.error||'label_unavailable'); location.href=data.labelUrl; } catch(err){setError(err.message.replaceAll('_',' '));} finally{setLoadingLabel(false);} };
  return <div className="portal-card"><h2>Shipment progress</h2><ol className="timeline"><li className="done">Request approved</li><li className={request.trackingUrl ? 'done' : ''}>{request.shippingMethod === 'prepaid_requested' ? 'Label request needs review—no postage purchased' : request.trackingUrl ? `${request.shippingCarrier} tracking active` : 'Label / tracking pending'}</li><li className={request.carrierStatus === 'delivered' ? 'done' : ''}>Carrier delivery</li><li>Physical receipt confirmation</li><li className={request.reimbursementStatus === 'paid' ? 'done' : ''}>Testing and any reimbursement</li></ol><div className="actions">{request.labelAvailable && <button className="button" disabled={loadingLabel} onClick={openLabel}>{loadingLabel?'Preparing label…':'Open prepaid label'}</button>}{request.trackingUrl && <a className="button secondary" href={request.trackingUrl} target="_blank" rel="noreferrer">View carrier tracking</a>}</div>{request.reimbursementStatus === 'paid' && <p>Your shipping reimbursement was marked paid {request.reimbursedAt ? new Date(request.reimbursedAt).toLocaleString() : ''}.</p>}</div>;
}

function Prepaid({ requestId, token, done, setError }) {
  const [sending, setSending] = useState(false);
  const [form, setForm] = useState({ name: '', company: '', street1: '', street2: '', city: '', state: '', zip: '', country: 'US', phone: '', length: '', width: '', height: '', weight: '', packageAccurate: false });
  const set = (key, value) => setForm(current => ({ ...current, [key]: value }));
  const submit = async event => { event.preventDefault(); setSending(true); setError(''); try {
    const response = await fetch(`/api/shipments/${encodeURIComponent(requestId)}/rates`, { method: 'POST', headers: {'content-type':'application/json'}, body: JSON.stringify({ token, packageAccurate: form.packageAccurate, fromAddress: { name: form.name, company: form.company, street1: form.street1, street2: form.street2, city: form.city, state: form.state, zip: form.zip, country: form.country, phone: form.phone }, parcel: { length: form.length, width: form.width, height: form.height, weight: form.weight } }) });
    const data = await response.json(); if (!response.ok && data.error !== 'no_eligible_rate_within_cap') throw new Error(data.error || 'label_generation_failed'); done(data.labelUrl ? { message: 'Your prepaid label is ready.', labelUrl: data.labelUrl, trackingNumber: data.trackingNumber } : { message: 'No eligible label fit the approved safeguards, so the request entered maintainer review without purchasing postage.' });
  } catch (err) { setError(err.message.replaceAll('_', ' ')); } finally { setSending(false); } };
  return <form className="portal-card" onSubmit={submit}><h2>Generate your prepaid label</h2><p>The return address is sent securely to the carrier platform and is not published. VivintOne chooses an eligible service within the approved spending cap. Weight is in ounces; dimensions are in inches.</p><div className="fields">
    {['name','company','street1','street2','city','state','zip','phone'].map(key => <div className={`field ${['street1','street2'].includes(key) ? 'full' : ''}`} key={key}><label htmlFor={key}>{({name:'Sender name',company:'Company (optional)',street1:'Street address',street2:'Apartment / suite (optional)',city:'City',state:'State',zip:'ZIP code',phone:'Phone for carrier'}[key])}</label><input id={key} required={!['company','street2'].includes(key)} value={form[key]} onChange={event => set(key,event.target.value)} /></div>)}
    <div className="field"><label htmlFor="country">Country</label><input id="country" maxLength="2" required value={form.country} onChange={event => set('country',event.target.value.toUpperCase())} /></div>
    {['length','width','height','weight'].map(key => <div className="field" key={key}><label htmlFor={key}>{key === 'weight' ? 'Weight (ounces)' : `${key[0].toUpperCase()+key.slice(1)} (inches)`}</label><input id={key} type="number" min="0.1" step="0.1" required value={form[key]} onChange={event => set(key,event.target.value)} /></div>)}
  </div><div className="checks"><div className="check"><input id="accurate" type="checkbox" required checked={form.packageAccurate} onChange={event => set('packageAccurate', event.target.checked)} /><label htmlFor="accurate">I measured the packed box and confirm the address, dimensions, and weight are accurate. Carrier adjustments caused by inaccurate information may make this offer ineligible.</label></div></div><div className="form-actions"><span /><button disabled={sending}>{sending ? 'Validating and generating…' : 'Generate prepaid label'}</button></div></form>;
}

function Manual({ requestId, token, request, trackingDone = false, done, setError }) {
  const [carrier, setCarrier] = useState(request.shippingCarrier || 'USPS'); const [trackingNumber, setTrackingNumber] = useState(''); const [sending, setSending] = useState(false);
  const [receipt, setReceipt] = useState(null); const [amount, setAmount] = useState(''); const [method, setMethod] = useState(''); const [destination, setDestination] = useState('');
  const tracking = async event => { event.preventDefault(); setSending(true); setError(''); try { const response = await fetch(`/api/shipments/${encodeURIComponent(requestId)}/tracking`, { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({token,carrier,trackingNumber})}); const data=await response.json(); if(!response.ok) throw new Error(data.error||'tracking_failed'); done('Tracking is active and tied to this request.'); } catch(err){setError(err.message.replaceAll('_',' '));} finally{setSending(false);} };
  const waive = async () => { setSending(true); setError(''); try { const response=await fetch(`/api/reimbursements/${encodeURIComponent(requestId)}/waive`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token})}); const data=await response.json(); if(!response.ok) throw new Error(data.error||'reimbursement_choice_failed'); done('Thank you for covering the shipping cost. No reimbursement will be requested for this shipment.'); } catch(err){setError(err.message.replaceAll('_',' '));} finally{setSending(false);} };
  const reimburse = async event => { event.preventDefault(); if(!receipt) return setError('choose a receipt image or PDF'); setSending(true); setError(''); try {
    const prepare=await fetch(`/api/reimbursements/${encodeURIComponent(requestId)}/upload`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token,contentType:receipt.type,size:receipt.size})}); const uploadData=await prepare.json(); if(!prepare.ok) throw new Error(uploadData.error||'upload_failed');
    const uploadForm=new FormData(); Object.entries(uploadData.upload.fields).forEach(([key,value])=>uploadForm.append(key,value)); uploadForm.append('file',receipt); const uploaded=await fetch(uploadData.upload.url,{method:'POST',body:uploadForm}); if(!uploaded.ok) throw new Error('receipt_upload_failed');
    const response=await fetch(`/api/reimbursements/${encodeURIComponent(requestId)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token,receiptKey:uploadData.receiptKey,amount,paymentMethod:method,paymentDestination:destination,carrier})}); const data=await response.json(); if(!response.ok) throw new Error(data.error||'reimbursement_failed'); done('Your receipt and reimbursement request were received. Payment remains locked until the hardware is physically received.');
  } catch(err){setError(err.message.replaceAll('_',' '));} finally{setSending(false);} };
  return <div className="portal-stack">{!trackingDone && !request.trackingUrl && <form className="portal-card" onSubmit={tracking}><h2>Register self-paid shipment</h2><div className="fields"><div className="field"><label htmlFor="carrier">Carrier</label><select id="carrier" value={carrier} onChange={e=>setCarrier(e.target.value)}><option>USPS</option><option>UPS</option><option>FedEx</option><option>Other</option></select></div><div className="field"><label htmlFor="tracking">Tracking number</label><input id="tracking" required value={trackingNumber} onChange={e=>setTrackingNumber(e.target.value)} /></div></div><div className="form-actions"><span/><button disabled={sending}>Save tracking</button></div></form>}
    {(request.trackingUrl || trackingDone) && !['submitted','paid','not_requested'].includes(request.reimbursementStatus) && <form className="portal-card" onSubmit={reimburse}><h2>Would you like shipping reimbursement?</h2><p>Reimbursement is optional. If requested, upload the carrier receipt and exact amount paid; payment is released only after physical receipt is confirmed.</p><div className="fields"><div className="field full"><label htmlFor="receipt">USPS / UPS / FedEx receipt</label><input id="receipt" type="file" accept="image/jpeg,image/png,application/pdf" required onChange={e=>setReceipt(e.target.files[0])}/><span className="hint">JPEG, PNG, or PDF; 10 MB maximum.</span></div><div className="field"><label htmlFor="amount">Amount paid (USD)</label><input id="amount" type="number" min="0.01" max="500" step="0.01" required value={amount} onChange={e=>setAmount(e.target.value)}/></div><div className="field"><label htmlFor="method">Repayment method</label><select id="method" required value={method} onChange={e=>setMethod(e.target.value)}><option value="">Choose</option><option value="venmo">Venmo</option><option value="zelle">Zelle</option><option value="paypal">PayPal</option></select></div><div className="field full"><label htmlFor="destination">Payment username, email, or phone</label><input id="destination" required value={destination} onChange={e=>setDestination(e.target.value)}/><span className="hint">Used only to complete this reimbursement; never shown publicly.</span></div></div><div className="form-actions"><button type="button" className="back" disabled={sending} onClick={waive}>No reimbursement needed</button><button disabled={sending}>{sending?'Uploading securely…':'Submit reimbursement'}</button></div></form>}
  </div>;
}

function Shell({ children }) { return <><header className="nav"><a className="brand" href="/">Vivint<span>One</span> / Hardware Lab</a><div><span>Private request</span></div></header><main className="portal">{children}</main><footer className="footer"><span>VivintOne by Mike Ziolkowski</span><span>Independent community project; not affiliated with Vivint.</span></footer></>; }
createRoot(document.getElementById('root')).render(<Portal />);
